### ISSUE TITLE
Scrollbar throws everything for a wonk

### ISSUE THREAD

**Issue by drusepth** [wooorm/write-music#6]
Whenever the text begins to scroll,

1. The scrollbar adjusts the content width, which throws off the background highlighting positioning.

![2017-03-14-165339_981x887_scrot](https://cloud.githubusercontent.com/assets/538235/23912167/c8d7afb0-08d6-11e7-8e0a-62af283fad69.png)

2. Scrolling scrolls the text, but the background highlighting doesn't seem to always scroll with it, often being off by several lines at a time.

![2017-03-14-165500_948x949_scrot](https://cloud.githubusercontent.com/assets/538235/23912253/07f2f416-08d7-11e7-8b13-bd6b57e407d8.png)

**Comment by wooorm** [comment]
Which browser, which os?

**Comment by drusepth** [comment]
Ah, sorry about that. The latest Google Chrome on Ubuntu 16 LTS.

**Comment by wooorm** [comment]
Hi @drusepth, sorry about the wait.

I only have access to OS X; so if you’d like I’d really appreciate a PR to fix this!

Anyway, I just pushed a possible fix, could you check if the site works now?

**Comment by drusepth** [comment]
No worries at all. I'm not using the project for anything currently; just saw it and was playing with it originally. 

Unfortunately the latest fix doesn't solve the issue, but I've opened up a PR (#8) that does (for me). Can you take a look and make sure it still works on OS X before potentially merging? :)
